---
title: "CSV to Dataframe"
author: "Rj"
date: 2019-04-22
description: "-"
type: technical_note
draft: false
---

In [1]:
import numpy as np
import pandas as pd

In [3]:
csv = pd.DataFrame.from_csv('uk-500.csv')

/Users/rajacsp/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.

##### Note

from_csv is deprecated

In [5]:
csv = pd.read_csv('uk-500.csv')

In [8]:
csv.head()

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk

In [9]:
csv.tail()

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web
495,Avery,Veit,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk
496,Reid,Euresti,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk
497,Charlette,Brenning,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk
498,Celestina,Keeny,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk
499,Mi,Richan,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk

In [10]:
csv.shape

(500, 11)

In [11]:
csv.describe()

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web
count,500,500,500,500,500,500,500,500,500,500,500
unique,479,498,498,500,468,102,500,500,500,500,498
top,Erasmo,Devereux,Martin Morrissey,860 Rokeby St,City and Hunslet Ward,Greater London,DA17 6EF,01943-467489,01992-655281,fernanda@writer.co.uk,http://www.martinmorrissey.co.uk
freq,3,2,2,1,3,44,1,1,1,1,2